# Generated by Django 2.1 on 2018-08-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owning_user', models.CharField(max_length=25)),
                ('ticker', models.CharField(max_length=6)),
            ],
        ),
    ]
